# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolumder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOtd', models.CharField(max_length=200)),
                ('NameTur', models.CharField(max_length=200)),
                ('NameKir', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lkp_God',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('God', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LkpOblast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOblast', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LkpRayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rayon', models.CharField(max_length=200)),
                ('KodOblast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LkpOblast')),
            ],
        ),
    ]
