# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_mytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='Adress_Home_Oblast',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Home_Rayon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Home_Selo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Home_Ulisa',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Sh_Oblast',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Sh_Rayon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Adress_Sh_Selo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Dr',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data rojdeniya'),
        ),
        migrations.AddField(
            model_name='mytable',
            name='God',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Korpus',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Nas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Pol',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='PoleNeprav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='PolePrav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='PoleProbel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Sh',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Telefon',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='t1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='t2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='t3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='t4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='t5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Lastname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='NameN',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Surname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
