# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20170416_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='DilB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='DilD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='DilY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SayB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SayD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SayY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SozB',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SozD',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SozY',
            field=models.IntegerField(default=0),
        ),
    ]
