# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20170416_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='StdSay',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
