# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_mytable_stdsay'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='DilSinav',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='EA',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='NomTerciha',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Otdelenie',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='mytable',
            name='Son',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SonDil',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SonSay',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='SonSoz',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='StdDil',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mytable',
            name='StdSoz',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
