# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20170416_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Home_Oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_home_oblast', to='App.LkpOblast'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Home_Rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_home_rayon', to='App.LkpRayon'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Sh_Oblast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_sh_oblast', to='App.LkpOblast'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Sh_Rayon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_sh_rayon', to='App.LkpRayon'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='God',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Lkp_God'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='NomTerciha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomTerciha', to='App.Bolumder'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Otdelenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otdelenie', to='App.Bolumder'),
        ),
    ]
