# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_auto_20170417_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Sifra',
            field=models.CharField(default='', max_length=200),
        ),
    ]
