# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_auto_20170417_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Sifra',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
