# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_auto_20170417_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Dr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
