# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20170417_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='t1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='t2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='t3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='t4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='t5',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
