# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_auto_20170417_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Home_Selo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Home_Ulisa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Adress_Sh_Selo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Korpus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Lastname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='NameN',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Nas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Pol',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Sh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Surname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Telefon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
