# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_auto_20170418_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rayonexp',
            name='ExpName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LkpRayon'),
        ),
    ]
