# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20170418_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolumder',
            name='NameOtd',
            field=models.CharField(max_length=100),
        ),
    ]
