# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_auto_20170418_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolumder',
            name='Kod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
