# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_bolumder_kod'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytable',
            name='God_Created',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
