# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-18 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_mytable_god_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PolK', models.CharField(max_length=200)),
                ('PolR', models.CharField(max_length=200)),
                ('PolT', models.CharField(max_length=200)),
            ],
        ),
    ]
