# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolumder',
            name='NumTandoo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
