# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_bolumder_numtandoo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolumder',
            name='NumTandoo',
            field=models.IntegerField(default=0),
        ),
    ]
