# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_auto_20170420_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='iv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bolum_pop', models.IntegerField(default=0)),
                ('bolum_average', models.DecimalField(blank=True, decimal_places=6, max_digits=12)),
                ('jer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.LkpOblast')),
            ],
        ),
    ]
