# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-24 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_auto_20170424_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bolumder',
            name='Orun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bolumder',
            name='Type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
