# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_auto_20170426_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bolumder',
            name='Kod',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Otdelenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otdelenie', to='App.Bolumder', to_field='Kod'),
        ),
    ]
