# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20170426_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytable',
            name='id',
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Otdelenie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='otdelenie', serialize=False, to='App.Bolumder', to_field='Kod'),
        ),
    ]
