# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_auto_20170426_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='averageBol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='bolumder',
            name='Kod',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='NomTerciha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nomTerciha', to='App.Bolumder'),
        ),
        migrations.AlterField(
            model_name='mytable',
            name='Otdelenie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otdelenie', to='App.Bolumder'),
        ),
        migrations.AddField(
            model_name='averagebol',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Bolumder'),
        ),
    ]
