# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_auto_20170430_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='averagebol',
            old_name='name',
            new_name='averageBolId',
        ),
    ]
