# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_auto_20170430_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Bolumder')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.MyTable')),
            ],
        ),
    ]
