# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0031_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='mesto',
            field=models.IntegerField(default=0),
        ),
    ]
