# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_last_mesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='ball',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
