# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0033_last_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='last',
            name='average',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.averageBol'),
        ),
    ]
