# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-12 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_last_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagebol',
            name='maxElement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='averagebol',
            name='minElement',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
